- name: template
  hosts: localhost
  become: true
  connection: local
  vars:
    my_port: 80
    my_path: /var/www/html/myweb
  tasks:
    - name: nginx install
      apt: name=nginx state=present
    - name: nginx start
      service: name=nginx state=started
    - name: create directory
      file: path=/var/www/html/myweb state=directory
    - name: copy index.html
      copy: src=./index.html dest=/var/www/html/myweb
    - name: copy myconfig.conf
      template: src=./myconfi.conf dest=/etc/nginx/sites-enabled/default
    - name: reload nginx
      service: name=nginx state=reloaded
