- name: file
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: create file
      file:
         name: myfile.txt
         state: touch
    - name: create directory
      file:
         name: mydir
         state: directory
    - name: copy file
      copy:
         src: myfile.txt
         dest: mydir/
