- name: LEMP on differnet os
  hosts: webserver
  become: true
  tasks:
     - name: dnf update
       dnf:
         name: "*"
         state: latest
       when: ansible_os_family== "RedHat"
     - name: install lemp on amazon
       dnf:
         name: "{{ item }}"
         state: present
       with_items:
         - nginx
         - php
         - mariadb105-server
       when: ansible_os_family== "RedHat"
     - name: started services on amazon
       service:
         name: "{{ item }}"
         state: started
       with_items:
         - nginx
         - php-fpm
         - mariadb
       when: ansible_os_family== "RedHat"
     - name: atp update
       apt:
         name: "*"
         state: latest
       when: ansible_os_family== "Debian"
     - name: install services
       apt:
         name: "{{ item }}"
         state: present
       with_items:
         - nginx
         - php
         - php8.3-fpm
         - mariadb-server
       when: ansible_os_family== "Debian"
     - name: stop apache
       service:
         name: apache2
         state: stopped
       when: ansible_os_family== "Debian"
     - name: start services
       service:
         name: "{{ item }}"
         state: started
       with_items:
         - nginx
         - php8.3-fpm
         - mariadb
       when: ansible_os_family== "Debian"
