- name: three tier archetacture
  hosts: all
  become: true
  tasks:
     - name: apt update
       shell: "apt update"
     - name: nginx install
       apt: name=nginx state=present
       when: inventory_hostname in groups ['webserver']
     - name: nginx start
       service: name=nginx state=started
       when: inventory_hostname in groups ['webserver']
     - name: php nstall
       apt: name="{{ item }}" state=present
       with_items:
         - php
         - php8.3-fpm
       when: inventory_hostname in groups ['appserver']
     - name: start php
       service: name=php8.3-fpm state=started
       when: inventory_hostname in groups ['appserver']
     - name: install mariadb
       apt: name=mariadb-server state=present
       when: inventory_hostname in groups ['dbserver']
     - name: start mariadb
       service: name=mariadb state=started
       when: inventory_hostname in groups ['dbserver']
